[package]
authors = ["eikendev"]
name = "turs"
version = "0.0.4"
description = "A Purs-inspired prompt"
edition = "2018"
homepage = "https://github.com/eikendev/turs"
repository = "https://github.com/eikendev/turs.git"
readme = "README.md"
license = "MIT"

[dependencies]
ansi_term = "^0.9"
clap = "^2.26.1"
dirs = "^1.0.0"
git2 = "^0.8"
tico = "^1.0.0"
